#!/usr/bin/env python3
"""Extract human-written passages from public-domain sources into a committed corpus.

The control corpus has to be genuinely human-written, or the false-positive act
teaches a lie. Every passage here comes from a pre-1930 public-domain work by a
named author, recorded with its source so the claim can be checked rather than
trusted. Nothing in this corpus was generated by a model.

Run once against downloaded Project Gutenberg texts; the extracted passages are
committed so the build needs no network.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "reference"))

import declawd  # noqa: E402

# Gutenberg id -> (author, short title, calibration or evaluation split).
# The split is by author, so no evaluation author is seen during calibration.
# Author death years are recorded because the site is published from the UK,
# where copyright runs for the author's life plus 70 years. Every author here
# died before 1955, so these works are public domain in the UK as well as the US.
# That covers the authors' own words only, which is why the extractor works hard
# to exclude the modern introductions and biographies Gutenberg files carry.
SOURCES = {
    14474: ("Michael Faraday", "The Chemical History of a Candle", "calibration"),
    34901: ("John Stuart Mill", "On Liberty", "calibration"),
    205: ("Henry David Thoreau", "Walden", "calibration"),
    833: ("Thorstein Veblen", "The Theory of the Leisure Class", "calibration"),
    3300: ("Adam Smith", "The Wealth of Nations", "calibration"),
    20203: ("Benjamin Franklin", "Autobiography", "calibration"),
    2009: ("Charles Darwin", "The Origin of Species", "calibration"),
    9662: ("David Hume", "An Enquiry Concerning Human Understanding", "calibration"),
    33310: ("David Ricardo", "Principles of Political Economy", "evaluation"),
    10615: ("John Locke", "An Essay Concerning Human Understanding", "evaluation"),
    26716: ("John Ruskin", "The Crown of Wild Olive", "evaluation"),
    24527: ("John Tyndall", "Fragments of Science", "evaluation"),
    16643: ("Ralph Waldo Emerson", "Essays", "evaluation"),
    4239: ("T. R. Malthus", "An Essay on the Principle of Population", "evaluation"),
    2931: ("Thomas Henry Huxley", "Evidence as to Man's Place in Nature", "evaluation"),
    147: ("Thomas Paine", "Common Sense", "evaluation"),
}

START = re.compile(r"\*\*\* START OF (THE|THIS) PROJECT GUTENBERG.*?\*\*\*", re.I)
END = re.compile(r"\*\*\* END OF (THE|THIS) PROJECT GUTENBERG.*?\*\*\*", re.I)

TARGET_CONTEXTS = 200
PASSAGES_PER_SOURCE = 12

# Front matter is where the material that is not the author's own lives:
# publisher series notes, editor introductions, biographies, transcriber notes.
# Skipping it is the single most effective filter.
SKIP_FRACTION = 0.30
STOP_FRACTION = 0.92

# Any paragraph containing one of these is not the author writing.
EDITORIAL = re.compile(
    r"gutenberg|transcriber|e-?book|produced by|proofread|distributed proofreading"
    r"|this series of books|these volumes|the present edition|this edition"
    r"|the editor|edited by|introduction by|translator|printed by|reprinted"
    r"|copyright|all rights reserved|footnote|\bpublisher\b|\bpreface\b"
    r"|was born (on|in)|died (on|in|at)|his biographer|in later life he"
    r"|university press|\bLL\.D\b|\bM\.A\b",
    re.I,
)


def strip_boilerplate(raw: str) -> str:
    start = START.search(raw)
    end = END.search(raw)
    body = raw[start.end() if start else 0 : end.start() if end else len(raw)]
    return body.replace("\r\n", "\n")


def paragraphs(body: str, surname: str):
    """Yield the author's own prose, skipping front matter and editorial material."""
    blocks = re.split(r"\n\s*\n", body)
    start = int(len(blocks) * SKIP_FRACTION)
    stop = int(len(blocks) * STOP_FRACTION)
    # A biography talks about the author in the third person; the author does not.
    about_author = re.compile(r"\b" + re.escape(surname) + r"(\'s)?\b\s+(was|had|is|has|would|became|wrote|died)", re.I)
    for block in blocks[start:stop]:
        text = " ".join(block.split())
        if len(text) < 200:
            continue
        if text.isupper() or text.startswith("[") or "_" in text[:40]:
            continue
        if not text[0].isupper():
            continue
        if EDITORIAL.search(text) or about_author.search(text):
            continue
        yield text


def tidy(text: str) -> str:
    """Normalise typographic noise that is an artefact of transcription, not authorship."""
    text = text.replace("“", '"').replace("”", '"')
    text = text.replace("‘", "'").replace("’", "'")
    text = text.replace("—", ", ").replace("–", "-")
    text = "".join(c for c in unicodedata.normalize("NFC", text) if c.isprintable())
    return " ".join(text.split())


def extract(body: str, wanted: int, surname: str) -> list[str]:
    out: list[str] = []
    buffer: list[str] = []
    for para in paragraphs(body, surname):
        buffer.append(tidy(para))
        candidate = " ".join(buffer)
        if declawd.count_contexts(candidate) >= TARGET_CONTEXTS:
            out.append(candidate)
            buffer = []
            if len(out) >= wanted:
                break
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--downloads", type=Path, required=True,
                        help="directory holding pgNNNN.txt files")
    parser.add_argument("--out", type=Path, default=ROOT / "fixtures" / "corpus.json")
    args = parser.parse_args()

    corpus = []
    for gid, (author, title, split) in sorted(SOURCES.items()):
        path = args.downloads / f"pg{gid}.txt"
        if not path.exists():
            print(f"[failed] missing {path}", file=sys.stderr)
            return 1
        raw = path.read_bytes().decode("utf-8", errors="replace")
        passages = extract(strip_boilerplate(raw), PASSAGES_PER_SOURCE, author.split()[-1])
        if len(passages) < PASSAGES_PER_SOURCE:
            print(f"[failed] {author}: only {len(passages)} passages", file=sys.stderr)
            return 1
        for index, text in enumerate(passages):
            corpus.append({
                "id": f"pg{gid}-{index:02d}",
                "author": author,
                "title": title,
                "gutenberg_id": gid,
                "split": split,
                "text": text,
            })
        print(f"[ok] {author}: {len(passages)} passages")

    payload = {
        "note": "Human-written public-domain passages. Nothing here was model-generated. "
                "Front matter, editorial introductions and biographical material are "
                "excluded, so each passage is the named author's own prose.",
        "licence": "The works are in the public domain in the United Kingdom and the "
                   "United States: every author died before 1955, so the UK term of "
                   "life plus 70 years has expired. Transcriptions were obtained from "
                   "Project Gutenberg, and all Project Gutenberg headers, footers, "
                   "notices and branding are stripped rather than redistributed.",
        "target_contexts": TARGET_CONTEXTS,
        "passages": corpus,
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_bytes(
        (json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n").encode("utf-8")
    )
    authors = {p["author"] for p in corpus}
    print(f"[ok] {len(corpus)} passages from {len(authors)} authors -> {args.out.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
