#!/usr/bin/env python3
"""Generate and validate the reproducible CycloneDX release SBOM."""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
import os
from pathlib import Path
import re
import secrets
import shutil
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
TOOL_VERSION = "0.5.9"
SPEC_VERSION = "1.5"


def package_version() -> str:
    match = re.search(
        r'^version = "([^"]+)"$',
        (ROOT / "Cargo.toml").read_text(encoding="utf-8"),
        re.MULTILINE,
    )
    if not match:
        raise ValueError("Cargo.toml package version is missing")
    return match.group(1)


def git_value(format_string: str) -> str:
    return subprocess.check_output(
        ["git", "show", "-s", f"--format={format_string}", "HEAD"],
        cwd=ROOT,
        text=True,
    ).strip()


def expected_timestamp(epoch: int) -> str:
    value = datetime.fromtimestamp(epoch, timezone.utc)
    return value.strftime("%Y-%m-%dT%H:%M:%S.000000000Z")


def normalise(document: dict, version: str, source_revision: str) -> None:
    metadata = document["metadata"]
    root = metadata["component"]
    old_root_ref = root["bom-ref"]
    stable_root_ref = f"pkg:cargo/declawd@{version}"
    root["bom-ref"] = stable_root_ref
    root["purl"] = stable_root_ref

    nested_refs = {}
    paths_by_type = {"library": "src/lib.rs", "application": "src/main.rs"}
    for component in root.get("components", []):
        path = paths_by_type.get(component.get("type"))
        if component.get("name") != "declawd" or path is None:
            raise ValueError("unexpected Declawd target in generated SBOM")
        old_ref = component["bom-ref"]
        stable_ref = f"{stable_root_ref}#{path}"
        nested_refs[old_ref] = stable_ref
        component["bom-ref"] = stable_ref
        component["purl"] = stable_ref

    for dependency in document.get("dependencies", []):
        if dependency["ref"] == old_root_ref:
            dependency["ref"] = stable_root_ref
        elif dependency["ref"] in nested_refs:
            dependency["ref"] = nested_refs[dependency["ref"]]
        dependency["dependsOn"] = [
            stable_root_ref if value == old_root_ref else nested_refs.get(value, value)
            for value in dependency.get("dependsOn", [])
        ]

    properties = metadata.setdefault("properties", [])
    properties.append({"name": "declawd:source_revision", "value": source_revision})


def component_refs(component: dict) -> list[str]:
    refs = [component["bom-ref"]]
    for child in component.get("components", []):
        refs.extend(component_refs(child))
    return refs


def validate(
    document: dict,
    version: str,
    source_revision: str,
    source_epoch: int,
) -> None:
    if document.get("bomFormat") != "CycloneDX":
        raise ValueError("SBOM is not CycloneDX")
    if document.get("specVersion") != SPEC_VERSION:
        raise ValueError(f"SBOM must use CycloneDX {SPEC_VERSION}")
    if document.get("version") != 1 or document.get("serialNumber") is not None:
        raise ValueError("SBOM must have deterministic version 1 without a serial number")

    metadata = document.get("metadata", {})
    if metadata.get("timestamp") != expected_timestamp(source_epoch):
        raise ValueError("SBOM timestamp does not match SOURCE_DATE_EPOCH")
    tools = metadata.get("tools", [])
    if not any(
        tool.get("name") == "cargo-cyclonedx" and tool.get("version") == TOOL_VERSION
        for tool in tools
    ):
        raise ValueError(f"SBOM was not generated by cargo-cyclonedx {TOOL_VERSION}")

    root = metadata.get("component", {})
    stable_ref = f"pkg:cargo/declawd@{version}"
    if (
        root.get("type") != "application"
        or root.get("name") != "declawd"
        or root.get("version") != version
        or root.get("bom-ref") != stable_ref
        or root.get("purl") != stable_ref
    ):
        raise ValueError("SBOM root component does not match the package")
    properties = {
        item.get("name"): item.get("value")
        for item in metadata.get("properties", [])
    }
    if properties.get("cdx:rustc:sbom:target:all_targets") != "true":
        raise ValueError("SBOM does not cover all declared build targets")
    if properties.get("declawd:source_revision") != source_revision:
        raise ValueError("SBOM source revision does not match the release commit")

    components = document.get("components", [])
    if not components:
        raise ValueError("SBOM has no dependency components")
    if not any(
        item.get("name") == "c2pa" and item.get("version") == "0.90.12"
        for item in components
    ):
        raise ValueError("SBOM does not contain the exact c2pa dependency")

    all_refs = component_refs(root)
    for component in components:
        all_refs.extend(component_refs(component))
    refs = set(all_refs)
    if len(refs) != len(all_refs):
        raise ValueError("SBOM contains duplicate component references")
    for dependency in document.get("dependencies", []):
        if dependency.get("ref") not in refs:
            raise ValueError(f"SBOM dependency has an unknown ref: {dependency.get('ref')}")
        unknown = set(dependency.get("dependsOn", [])) - refs
        if unknown:
            raise ValueError(f"SBOM dependency points to unknown refs: {sorted(unknown)}")

    encoded = json.dumps(document, ensure_ascii=False)
    if "file://" in encoded or "path+file:" in encoded:
        raise ValueError("SBOM contains a checkout-specific file path")


def generate(destination: Path, source_revision: str, source_epoch: int) -> None:
    tool = shutil.which("cargo-cyclonedx")
    if not tool:
        raise ValueError(
            f"cargo-cyclonedx {TOOL_VERSION} is required; install the exact pinned version"
        )
    reported = subprocess.check_output(
        [tool, "cyclonedx", "--version"], text=True
    ).strip()
    if reported != f"cargo-cyclonedx-cyclonedx {TOOL_VERSION}":
        raise ValueError(
            f"expected cargo-cyclonedx {TOOL_VERSION}, found {reported!r}"
        )

    prefix = f".declawd-sbom-{secrets.token_hex(8)}.cdx"
    generated = ROOT / f"{prefix}.json"
    environment = os.environ.copy()
    environment["SOURCE_DATE_EPOCH"] = str(source_epoch)
    try:
        subprocess.run(
            [
                tool,
                "cyclonedx",
                "--format",
                "json",
                "--spec-version",
                SPEC_VERSION,
                "--target",
                "all",
                "--override-filename",
                prefix,
                "--quiet",
            ],
            cwd=ROOT,
            env=environment,
            check=True,
        )
        document = json.loads(generated.read_text(encoding="utf-8"))
        version = package_version()
        normalise(document, version, source_revision)
        validate(document, version, source_revision, source_epoch)
        if destination.exists():
            raise ValueError(f"refusing to overwrite existing SBOM: {destination}")
        if not destination.parent.is_dir():
            raise ValueError(f"SBOM output directory does not exist: {destination.parent}")
        destination.write_text(
            json.dumps(document, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
    finally:
        generated.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path)
    parser.add_argument("--validate", type=Path)
    parser.add_argument("--source-revision")
    parser.add_argument("--source-date-epoch", type=int)
    args = parser.parse_args()
    if (args.output is None) == (args.validate is None):
        parser.error("choose exactly one of --output or --validate")

    source_revision = args.source_revision or git_value("%H")
    source_epoch = (
        args.source_date_epoch
        if args.source_date_epoch is not None
        else int(git_value("%ct"))
    )
    version = package_version()
    if not re.fullmatch(r"[0-9a-f]{40}", source_revision):
        raise ValueError("source revision must be a full lowercase Git commit SHA")
    if source_epoch < 0:
        raise ValueError("source date epoch must be non-negative")
    if args.validate:
        document = json.loads(args.validate.read_text(encoding="utf-8"))
        validate(document, version, source_revision, source_epoch)
        print(f"verified CycloneDX {SPEC_VERSION} SBOM {args.validate}")
    else:
        destination = args.output if args.output.is_absolute() else ROOT / args.output
        generate(destination, source_revision, source_epoch)
        print(f"wrote reproducible CycloneDX {SPEC_VERSION} SBOM {destination}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, subprocess.CalledProcessError, json.JSONDecodeError) as error:
        print(f"SBOM error: {error}", file=sys.stderr)
        raise SystemExit(1)
